apiVersion: v1
kind: Service
metadata:
  name: milvus-db-service
  labels:
    app: milvus
spec:
  ports:
    - port: 19530
      targetPort: 19530
  selector:
    app: milvus
    tier: db
  type: NodePort

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: milvus-db-claim
  labels:
    app: milvus
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: milvus-db-deployment
  labels:
    app: milvus
spec: 
  selector:
    matchLabels:
      app: milvus
      tier: db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: milvus
        tier: db
    spec:
      containers:
      - image: milvus-standalone:1.0
        name: milvus
        ports:
        - containerPort: 19530
          name: milvus
        volumeMounts:
        - name: milvus-persistent-storage
          mountPath: var/lib/milvus
      volumes:
      - name: milvus-persistent-storage
        persistentVolumeClaim:
          claimName: milvus-db-claim

