# This file was generated by liblab | https://liblab.com/

from .utils.json_map import JsonMap
from .base import BaseModel


@JsonMap({"db_name": "dbName"})
class CollectionListRequest(BaseModel):
    """CollectionListRequest

    :param db_name: db_name
    :type db_name: str
    :type host: str
    """

    def __init__(self, db_name: str, host: str):
        self.db_name = db_name
        self.host = host
