# This file was generated by liblab | https://liblab.com/

from .utils.json_map import JsonMap
from .base import BaseModel


@JsonMap({"db_name": "dbName", "collection_name": "collectionName"})
class CollectionLoadRequest(BaseModel):
    """CollectionLoadRequest

    :param db_name: db_name, defaults to "default"
    :type db_name: str, optional
    :param collection_name: collection_name
    :type collection_name: str
    """

    def __init__(self, collection_name: str, db_name: str = "default"):
        if db_name is not None:
            self.db_name = db_name
        self.collection_name = collection_name
