# This file was generated by liblab | https://liblab.com/

from typing import List
from .utils.json_map import JsonMap
from .base import BaseModel


@JsonMap(
    {
        "db_name": "dbName",
        "collection_name": "collectionName",
        "partition_names": "partitionNames",
        "output_fields": "outputFields",
    }
)
class CreateVectorsQueryRequest(BaseModel):
    """CreateVectorsQueryRequest

    :param db_name: db_name, defaults to None
    :type db_name: str, optional
    :param collection_name: collection_name
    :type collection_name: str
    :param partition_names: partition_names, defaults to None
    :type partition_names: List[str], optional
    :param filter: filter
    :type filter: str
    :param output_fields: output_fields, defaults to None
    :type output_fields: List[str], optional
    """

    def __init__(
        self,
        collection_name: str,
        filter: str,
        db_name: str = None,
        partition_names: List[str] = None,
        output_fields: List[str] = None,
    ):
        if db_name is not None:
            self.db_name = db_name
        self.collection_name = collection_name
        if partition_names is not None:
            self.partition_names = partition_names
        self.filter = filter
        if output_fields is not None:
            self.output_fields = output_fields
