# This file was generated by liblab | https://liblab.com/

from .utils.json_map import JsonMap
from .base import BaseModel


@JsonMap(
    {
        "db_name": "dbName",
        "collection_name": "collectionName",
        "partition_name": "partitionName",
    }
)
class CreateVectorsDeleteRequest(BaseModel):
    """CreateVectorsDeleteRequest

    :param db_name: db_name, defaults to None
    :type db_name: str, optional
    :param collection_name: collection_name
    :type collection_name: str
    :param filter: filter
    :type filter: str
    :param partition_name: partition_name, defaults to None
    :type partition_name: str, optional
    """

    def __init__(
        self,
        collection_name: str,
        filter: str,
        host: str,
        db_name: str = None,
        partition_name: str = None,
    ):
        if db_name is not None:
            self.db_name = db_name
        self.collection_name = collection_name
        self.filter = filter
        if partition_name is not None:
            self.partition_name = partition_name
        if host is not None:
            self.host = host
