# This file was generated by liblab | https://liblab.com/

from .utils.json_map import JsonMap
from .base import BaseModel


@JsonMap({"db_name": "dbName"})
class CreateCollectionsListRequest(BaseModel):
    """CreateCollectionsListRequest

    :param db_name: db_name
    :type db_name: str
    """

    def __init__(self, db_name: str):
        self.db_name = db_name
