# This file was generated by liblab | https://liblab.com/

from .utils.json_map import JsonMap
from .base import BaseModel


@JsonMap(
    {
        "db_name": "dbName",
        "collection_name": "collectionName",
        "partition_names": "partitionNames",
    }
)
class CreateCollectionsGetLoadStateRequest(BaseModel):
    """CreateCollectionsGetLoadStateRequest

    :param db_name: db_name, defaults to None
    :type db_name: str, optional
    :param collection_name: collection_name
    :type collection_name: str
    :param partition_names: partition_names, defaults to None
    :type partition_names: str, optional
    """

    def __init__(
        self, collection_name: str, db_name: str = None, partition_names: str = None
    ):
        if db_name is not None:
            self.db_name = db_name
        self.collection_name = collection_name
        if partition_names is not None:
            self.partition_names = partition_names
