# This file was generated by liblab | https://liblab.com/

from .utils.json_map import JsonMap
from .base import BaseModel


@JsonMap(
    {
        "db_name": "dbName",
        "collection_name": "collectionName",
        "new_collection_name": "newCollectionName",
    }
)
class CreateCollectionsRenameRequest(BaseModel):
    """CreateCollectionsRenameRequest

    :param db_name: db_name, defaults to None
    :type db_name: str, optional
    :param collection_name: collection_name
    :type collection_name: str
    :param new_collection_name: new_collection_name
    :type new_collection_name: str
    """

    def __init__(
        self, collection_name: str, new_collection_name: str, db_name: str = None
    ):
        if db_name is not None:
            self.db_name = db_name
        self.collection_name = collection_name
        self.new_collection_name = new_collection_name
