// This file was generated by liblab | https://liblab.com/

package io.gandi.examples;

import io.gandi.Gandi;
import io.gandi.exceptions.ApiException;

public class Main {

  public static void main(String[] args) {
    Gandi client = new Gandi(System.getenv("GANDI_BEARER_TOKEN"));
    // No Default service was specified
  }
}
