// This file was generated by liblab | https://liblab.com/

package io.gandi.services;

import static org.junit.Assert.assertTrue;

import io.gandi.models.*;
import org.junit.jupiter.api.*;

class CollectionsServiceTest {
  // @CollectionsServiceTest

  // @DisplayName("Test that Collections is working")

  // public void test() {}

  // TODO: Write tests for create

  // TODO: Write tests for create2

  // TODO: Write tests for create3

  // TODO: Write tests for create4

  // TODO: Write tests for create5

  // TODO: Write tests for create6

  // TODO: Write tests for create7

  // TODO: Write tests for create8

  // TODO: Write tests for create9

  // TODO: Write tests for create10

}
