// This file was generated by liblab | https://liblab.com/

package io.gandi.services;

import static org.junit.Assert.assertTrue;

import io.gandi.models.*;
import org.junit.jupiter.api.*;

class IndexesServiceTest {
  // @IndexesServiceTest

  // @DisplayName("Test that Indexes is working")

  // public void test() {}

  // TODO: Write tests for create11

  // TODO: Write tests for create12

  // TODO: Write tests for create13

  // TODO: Write tests for create14

}
