// This file was generated by liblab | https://liblab.com/

package indexes

type IndexDescribeRequest struct {
	DbName         *string `json:"dbName,omitempty"`
	CollectionName *string `json:"collectionName,omitempty" required:"true"`
	IndexName      *string `json:"indexName,omitempty" required:"true"`
}

func (c *IndexDescribeRequest) SetDbName(dbName string) {
	c.DbName = &dbName
}

func (c *IndexDescribeRequest) GetDbName() *string {
	if c == nil {
		return nil
	}
	return c.DbName
}

func (c *IndexDescribeRequest) SetCollectionName(collectionName string) {
	c.CollectionName = &collectionName
}

func (c *IndexDescribeRequest) GetCollectionName() *string {
	if c == nil {
		return nil
	}
	return c.CollectionName
}

func (c *IndexDescribeRequest) SetIndexName(indexName string) {
	c.IndexName = &indexName
}

func (c *IndexDescribeRequest) GetIndexName() *string {
	if c == nil {
		return nil
	}
	return c.IndexName
}
