// This file was generated by liblab | https://liblab.com/

package indexes

type IndexDropRequest struct {
	DbName         *string `json:"dbName,omitempty"`
	CollectionName *string `json:"collectionName,omitempty" required:"true"`
	IndexName      *string `json:"indexName,omitempty" required:"true"`
}

func (c *IndexDropRequest) SetDbName(dbName string) {
	c.DbName = &dbName
}

func (c *IndexDropRequest) GetDbName() *string {
	if c == nil {
		return nil
	}
	return c.DbName
}

func (c *IndexDropRequest) SetCollectionName(collectionName string) {
	c.CollectionName = &collectionName
}

func (c *IndexDropRequest) GetCollectionName() *string {
	if c == nil {
		return nil
	}
	return c.CollectionName
}

func (c *IndexDropRequest) SetIndexName(indexName string) {
	c.IndexName = &indexName
}

func (c *IndexDropRequest) GetIndexName() *string {
	if c == nil {
		return nil
	}
	return c.IndexName
}
