// This file was generated by liblab | https://liblab.com/

package indexes

type IndexRequest struct {
	DbName         *string                   `json:"dbName,omitempty"`
	CollectionName *string                   `json:"collectionName,omitempty" required:"true"`
	IndexParams    []IndexRequestIndexParams `json:"indexParams,omitempty"`
}

func (i *IndexRequest) SetDbName(dbName string) {
	i.DbName = &dbName
}

func (i *IndexRequest) GetDbName() *string {
	if i == nil {
		return nil
	}
	return i.DbName
}

func (i *IndexRequest) SetCollectionName(collectionName string) {
	i.CollectionName = &collectionName
}

func (i *IndexRequest) GetCollectionName() *string {
	if i == nil {
		return nil
	}
	return i.CollectionName
}

func (i *IndexRequest) SetIndexParams(indexParams []IndexRequestIndexParams) {
	i.IndexParams = indexParams
}

func (i *IndexRequest) GetIndexParams() []IndexRequestIndexParams {
	if i == nil {
		return nil
	}
	return i.IndexParams
}

type IndexRequestIndexParams struct {
	MetricType *string             `json:"metricType,omitempty"`
	FieldName  *string             `json:"fieldName,omitempty"`
	IndexName  *string             `json:"indexName,omitempty"`
	Params     *IndexParamsParams2 `json:"params,omitempty"`
}

func (i *IndexRequestIndexParams) SetMetricType(metricType string) {
	i.MetricType = &metricType
}

func (i *IndexRequestIndexParams) GetMetricType() *string {
	if i == nil {
		return nil
	}
	return i.MetricType
}

func (i *IndexRequestIndexParams) SetFieldName(fieldName string) {
	i.FieldName = &fieldName
}

func (i *IndexRequestIndexParams) GetFieldName() *string {
	if i == nil {
		return nil
	}
	return i.FieldName
}

func (i *IndexRequestIndexParams) SetIndexName(indexName string) {
	i.IndexName = &indexName
}

func (i *IndexRequestIndexParams) GetIndexName() *string {
	if i == nil {
		return nil
	}
	return i.IndexName
}

func (i *IndexRequestIndexParams) SetParams(params IndexParamsParams2) {
	i.Params = &params
}

func (i *IndexRequestIndexParams) GetParams() *IndexParamsParams2 {
	if i == nil {
		return nil
	}
	return i.Params
}

type IndexParamsParams2 struct {
	IndexType      *string `json:"index_type,omitempty"`
	M              *int64  `json:"M,omitempty"`
	EfConstruction *int64  `json:"efConstruction,omitempty"`
	Nlist          *int64  `json:"nlist,omitempty"`
}

func (i *IndexParamsParams2) SetIndexType(indexType string) {
	i.IndexType = &indexType
}

func (i *IndexParamsParams2) GetIndexType() *string {
	if i == nil {
		return nil
	}
	return i.IndexType
}

func (i *IndexParamsParams2) SetM(m int64) {
	i.M = &m
}

func (i *IndexParamsParams2) GetM() *int64 {
	if i == nil {
		return nil
	}
	return i.M
}

func (i *IndexParamsParams2) SetEfConstruction(efConstruction int64) {
	i.EfConstruction = &efConstruction
}

func (i *IndexParamsParams2) GetEfConstruction() *int64 {
	if i == nil {
		return nil
	}
	return i.EfConstruction
}

func (i *IndexParamsParams2) SetNlist(nlist int64) {
	i.Nlist = &nlist
}

func (i *IndexParamsParams2) GetNlist() *int64 {
	if i == nil {
		return nil
	}
	return i.Nlist
}
