# This file was generated by liblab | https://liblab.com/
# Don't forget pip install gandi
import sys

sys.path.append("router/liblab/python/src")

from gandi import Gandi
from gandi.models import *

coll_name = "test110"
host = "localhost:19530"

sdk = Gandi(access_token="YOUR_ACCESS_TOKEN", base_url="http://localhost:8080")

request_body = Collection(collection_name=coll_name, dimension=8, host=host)

result = sdk.collections.create(request_body=request_body)

"""
print(result)

result = sdk.collections.describe(
    CollectionDescribeRequest(collection_name=coll_name, host=host)
)
"""

print(result)

result = sdk.vectors.insert(
    VectorsInsertRequest(
        collection_name=coll_name,
        data=[{"vector": [i / 10] * 8, "id": i} for i in range(1, 10)],
        host=host,
    )
)

print(result)

result = sdk.vectors.get(
    VectorsGetRequest(collection_name=coll_name, id_=[1, 3, 5], host=host)
)

print(result)

result = sdk.vectors.delete(
    VectorsDeleteRequest(collection_name=coll_name, filter="id in [2, 4]", host=host)
)

print(result)


result = sdk.vectors.get(
    VectorsGetRequest(collection_name=coll_name, id_=[1, 2, 3, 4], host=host)
)

print(result)


print(
    sdk.collections.get_load_state(
        CollectionGetLoadStateRequest(collection_name=coll_name, host=host)
    )
)

print(
    sdk.collections.get_stats(
        CollectionGetStatsRequest(collection_name=coll_name, host=host)
    )
)

print(sdk.collections.has(CollectionHasRequest(collection_name=coll_name, host=host)))

print(sdk.collections.list(CollectionListRequest(db_name="default", host=host)))

print(
    sdk.collections.rename(
        CollectionRenameRequest(
            collection_name=coll_name, new_collection_name="hello123", host=host
        )
    )
)

print(
    sdk.collections.drop(CollectionDropRequest(collection_name="hello123", host=host))
)
