# This file was generated by liblab | https://liblab.com/
import sys

sys.path.append("router/liblab/python/src")

from gandi import Gandi
from gandi.models import (
    CollectionRequest,
    CreateVectorsInsertRequest,
    CreateVectorsGetRequest,
    CreateVectorsDeleteRequest,
    CreateCollectionsDescribeRequest,
)

coll_name = "test107"
host = "localhost:19530"

sdk = Gandi(access_token="YOUR_ACCESS_TOKEN", base_url="http://localhost:8080")

request_body = CollectionRequest(collection_name=coll_name, dimension=8, host=host)

result = sdk.collections.create_collections_create(request_body=request_body)

"""
print(result)

result = sdk.collections.create_collections_describe(
    CreateCollectionsDescribeRequest(collection_name=coll_name, host=host)
)
"""

print(result)

result = sdk.vectors.create_vectors_insert(
    CreateVectorsInsertRequest(
        collection_name=coll_name,
        data=[{"vector": [i / 10] * 8, "id": i} for i in range(1, 10)],
        host=host,
    )
)

print(result)

result = sdk.vectors.create_vectors_get(
    CreateVectorsGetRequest(collection_name=coll_name, id_=[1, 3, 5], host=host)
)

print(result)

result = sdk.vectors.create_vectors_delete(
    CreateVectorsDeleteRequest(
        collection_name=coll_name, filter="id in [2, 4]", host=host
    )
)

print(result)


result = sdk.vectors.create_vectors_get(
    CreateVectorsGetRequest(collection_name=coll_name, id_=[1, 2, 3, 4], host=host)
)

print(result)
