// This file was generated by liblab | https://liblab.com/

package io.gandi;

import lombok.RequiredArgsConstructor;

@RequiredArgsConstructor
public enum Environment {
  DEFAULT("https://api.gandi.io/v1");

  private final String url;

  public String getUrl() {
    return this.url;
  }
}
