// This file was generated by liblab | https://liblab.com/

package io.gandi;

import io.gandi.Environment;
import io.gandi.http.interceptors.BearerTokenInterceptor;
import io.gandi.http.interceptors.DefaultHeadersInterceptor;
import io.gandi.http.interceptors.RetryInterceptor;
import io.gandi.services.*;
import java.util.Map;
import okhttp3.OkHttpClient;

public class Gandi {

  public CollectionsService collectionsService;
  public IndexesService indexesService;
  public VectorsService vectorsService;

  private final BearerTokenInterceptor bearerTokenInterceptor = new BearerTokenInterceptor();

  public Gandi() {
    final String serverUrl = Environment.DEFAULT.getUrl();
    final OkHttpClient httpClient = new OkHttpClient.Builder()
      .addInterceptor(new DefaultHeadersInterceptor())
      .addInterceptor(new RetryInterceptor())
      .addInterceptor(bearerTokenInterceptor)
      .build();

    this.collectionsService = new CollectionsService(httpClient, serverUrl);
    this.indexesService = new IndexesService(httpClient, serverUrl);
    this.vectorsService = new VectorsService(httpClient, serverUrl);
  }

  public Gandi(String bearerToken) {
    this();
    setBearerToken(bearerToken);
  }

  public void setBaseUrl(String url) {
    this.collectionsService.setBaseUrl(url);
    this.indexesService.setBaseUrl(url);
    this.vectorsService.setBaseUrl(url);
  }

  public void setBearerToken(String token) {
    this.bearerTokenInterceptor.setBearerToken(token);
  }
}
// c029837e0e474b76bc487506e8799df5e3335891efe4fb02bda7a1441840310c
