// This file was generated by liblab | https://liblab.com/

package shared

import (
	"github.com/swagger-api/swagger-petstore/internal/clients/rest/httptransport"
)

type GandiResponse[T any] struct {
	Data     T
	Metadata GandiResponseMetadata
}

type GandiResponseMetadata struct {
	Headers    map[string]string
	StatusCode int
}

func NewGandiResponse[T any](resp *httptransport.Response[T]) *GandiResponse[T] {
	return &GandiResponse[T]{
		Data: resp.Data,
		Metadata: GandiResponseMetadata{
			StatusCode: resp.StatusCode,
			Headers:    resp.Headers,
		},
	}
}
