// This file was generated by liblab | https://liblab.com/

package shared

import (
	"github.com/swagger-api/swagger-petstore/internal/clients/rest/httptransport"
)

type GandiError struct {
	Err      error
	Body     []byte
	Metadata GandiErrorMetadata
}

type GandiErrorMetadata struct {
	Headers    map[string]string
	StatusCode int
}

func NewGandiError[T any](transportError *httptransport.ErrorResponse[T]) *GandiError {
	return &GandiError{
		Err:  transportError.GetError(),
		Body: transportError.GetBody(),
		Metadata: GandiErrorMetadata{
			StatusCode: transportError.GetStatusCode(),
			Headers:    transportError.GetHeaders(),
		},
	}
}

func (e *GandiError) Error() string {
	return e.Err.Error()
}
