// This file was generated by liblab | https://liblab.com/

package gandi

import (
	"github.com/swagger-api/swagger-petstore/internal/configmanager"
	"github.com/swagger-api/swagger-petstore/pkg/collections"
	"github.com/swagger-api/swagger-petstore/pkg/gandiconfig"
	"github.com/swagger-api/swagger-petstore/pkg/indexes"
	"github.com/swagger-api/swagger-petstore/pkg/vectors"
)

type Gandi struct {
	Collections *collections.CollectionsService
	Indexes     *indexes.IndexesService
	Vectors     *vectors.VectorsService
	manager     *configmanager.ConfigManager
}

func NewGandi(config gandiconfig.Config) *Gandi {
	manager := configmanager.NewConfigManager(config)
	return &Gandi{
		Collections: collections.NewCollectionsService(manager),
		Indexes:     indexes.NewIndexesService(manager),
		Vectors:     vectors.NewVectorsService(manager),
		manager:     manager,
	}
}

func (g *Gandi) SetBaseUrl(baseUrl string) {
	g.manager.SetBaseUrl(baseUrl)
}

func (g *Gandi) SetAccessToken(accessToken string) {
	g.manager.SetAccessToken(accessToken)
}

// c029837e0e474b76bc487506e8799df5e3335891efe4fb02bda7a1441840310c
