// This file was generated by liblab | https://liblab.com/

package main

import (
	"bufio"
	"context"
	"fmt"
	"os"
	"strings"

	"github.com/swagger-api/swagger-petstore/pkg/collections"
	"github.com/swagger-api/swagger-petstore/pkg/gandi"
	"github.com/swagger-api/swagger-petstore/pkg/gandiconfig"
)

func main() {
	loadEnv()

	config := gandiconfig.NewConfig()
	client := gandi.NewGandi(config)

	request := collections.CollectionRequest{}
	request.SetCollectionName("CollectionName")

	response, err := client.Collections.CreateCollectionsCreate(context.Background(), request)
	if err != nil {
		panic(err)
	}
	fmt.Printf("%+v", response)
}

func loadEnv() error {
	file, err := os.Open(".env")
	if err != nil {
		return err
	}
	defer file.Close()

	scanner := bufio.NewScanner(file)
	for scanner.Scan() {
		line := scanner.Text()
		parts := strings.SplitN(line, "=", 2)
		if len(parts) != 2 {
			continue
		}
		key := strings.TrimSpace(parts[0])
		value := strings.TrimSpace(parts[1])
		os.Setenv(key, value)
	}

	if err := scanner.Err(); err != nil {
		return err
	}

	return nil
}
