// This file was generated by liblab | https://liblab.com/

package vectors

import (
	"github.com/swagger-api/swagger-petstore/internal/marshal"
	"github.com/swagger-api/swagger-petstore/internal/unmarshal"
	"github.com/swagger-api/swagger-petstore/internal/utils"
)

type CreateVectorsInsertRequest struct {
	DbName         *string                                    `json:"dbName,omitempty"`
	CollectionName *string                                    `json:"collectionName,omitempty" required:"true"`
	PartitionName  *string                                    `json:"partitionName,omitempty"`
	Data           map[string]*CreateVectorsInsertRequestData `json:"data,omitempty"`
}

func (c *CreateVectorsInsertRequest) SetDbName(dbName string) {
	c.DbName = &dbName
}

func (c *CreateVectorsInsertRequest) GetDbName() *string {
	if c == nil {
		return nil
	}
	return c.DbName
}

func (c *CreateVectorsInsertRequest) SetCollectionName(collectionName string) {
	c.CollectionName = &collectionName
}

func (c *CreateVectorsInsertRequest) GetCollectionName() *string {
	if c == nil {
		return nil
	}
	return c.CollectionName
}

func (c *CreateVectorsInsertRequest) SetPartitionName(partitionName string) {
	c.PartitionName = &partitionName
}

func (c *CreateVectorsInsertRequest) GetPartitionName() *string {
	if c == nil {
		return nil
	}
	return c.PartitionName
}

func (c *CreateVectorsInsertRequest) SetData(data map[string]*CreateVectorsInsertRequestData) {
	c.Data = utils.CloneMap(data)
}

func (c *CreateVectorsInsertRequest) GetData() map[string]*CreateVectorsInsertRequestData {
	if c == nil {
		return nil
	}
	return c.Data
}

type CreateVectorsInsertRequestData struct {
	StringValue       *string
	IntegerValue      *int64
	NumberValue       *float64
	BooleanValue      *bool
	StringArrayValue  []string
	IntegerArrayValue []int64
	NumberArrayValue  []float64
	BooleanArrayValue []bool
}

func (c *CreateVectorsInsertRequestData) SetStringValue(stringValue string) {
	c.StringValue = &stringValue
}

func (c *CreateVectorsInsertRequestData) GetStringValue() *string {
	if c == nil {
		return nil
	}
	return c.StringValue
}

func (c *CreateVectorsInsertRequestData) SetIntegerValue(integerValue int64) {
	c.IntegerValue = &integerValue
}

func (c *CreateVectorsInsertRequestData) GetIntegerValue() *int64 {
	if c == nil {
		return nil
	}
	return c.IntegerValue
}

func (c *CreateVectorsInsertRequestData) SetNumberValue(numberValue float64) {
	c.NumberValue = &numberValue
}

func (c *CreateVectorsInsertRequestData) GetNumberValue() *float64 {
	if c == nil {
		return nil
	}
	return c.NumberValue
}

func (c *CreateVectorsInsertRequestData) SetBooleanValue(booleanValue bool) {
	c.BooleanValue = &booleanValue
}

func (c *CreateVectorsInsertRequestData) GetBooleanValue() *bool {
	if c == nil {
		return nil
	}
	return c.BooleanValue
}

func (c *CreateVectorsInsertRequestData) SetStringArrayValue(stringArrayValue []string) {
	c.StringArrayValue = stringArrayValue
}

func (c *CreateVectorsInsertRequestData) GetStringArrayValue() []string {
	if c == nil {
		return nil
	}
	return c.StringArrayValue
}

func (c *CreateVectorsInsertRequestData) SetIntegerArrayValue(integerArrayValue []int64) {
	c.IntegerArrayValue = integerArrayValue
}

func (c *CreateVectorsInsertRequestData) GetIntegerArrayValue() []int64 {
	if c == nil {
		return nil
	}
	return c.IntegerArrayValue
}

func (c *CreateVectorsInsertRequestData) SetNumberArrayValue(numberArrayValue []float64) {
	c.NumberArrayValue = numberArrayValue
}

func (c *CreateVectorsInsertRequestData) GetNumberArrayValue() []float64 {
	if c == nil {
		return nil
	}
	return c.NumberArrayValue
}

func (c *CreateVectorsInsertRequestData) SetBooleanArrayValue(booleanArrayValue []bool) {
	c.BooleanArrayValue = booleanArrayValue
}

func (c *CreateVectorsInsertRequestData) GetBooleanArrayValue() []bool {
	if c == nil {
		return nil
	}
	return c.BooleanArrayValue
}

func (c CreateVectorsInsertRequestData) MarshalJSON() ([]byte, error) {
	return marshal.FromComplexObject(c)
}

func (c *CreateVectorsInsertRequestData) UnmarshalJSON(data []byte) error {
	return unmarshal.ToComplexObject[CreateVectorsInsertRequestData](data, c)
}
