// This file was generated by liblab | https://liblab.com/

package vectors

import (
	"github.com/swagger-api/swagger-petstore/internal/marshal"
	"github.com/swagger-api/swagger-petstore/internal/unmarshal"
	"github.com/swagger-api/swagger-petstore/internal/utils"
)

type CreateVectorsUpsertRequest struct {
	DbName         *string                                    `json:"dbName,omitempty"`
	CollectionName *string                                    `json:"collectionName,omitempty" required:"true"`
	PartitionName  *string                                    `json:"partitionName,omitempty"`
	Data           map[string]*CreateVectorsUpsertRequestData `json:"data,omitempty"`
}

func (c *CreateVectorsUpsertRequest) SetDbName(dbName string) {
	c.DbName = &dbName
}

func (c *CreateVectorsUpsertRequest) GetDbName() *string {
	if c == nil {
		return nil
	}
	return c.DbName
}

func (c *CreateVectorsUpsertRequest) SetCollectionName(collectionName string) {
	c.CollectionName = &collectionName
}

func (c *CreateVectorsUpsertRequest) GetCollectionName() *string {
	if c == nil {
		return nil
	}
	return c.CollectionName
}

func (c *CreateVectorsUpsertRequest) SetPartitionName(partitionName string) {
	c.PartitionName = &partitionName
}

func (c *CreateVectorsUpsertRequest) GetPartitionName() *string {
	if c == nil {
		return nil
	}
	return c.PartitionName
}

func (c *CreateVectorsUpsertRequest) SetData(data map[string]*CreateVectorsUpsertRequestData) {
	c.Data = utils.CloneMap(data)
}

func (c *CreateVectorsUpsertRequest) GetData() map[string]*CreateVectorsUpsertRequestData {
	if c == nil {
		return nil
	}
	return c.Data
}

type CreateVectorsUpsertRequestData struct {
	StringValue       *string
	IntegerValue      *int64
	NumberValue       *float64
	BooleanValue      *bool
	StringArrayValue  []string
	IntegerArrayValue []int64
	NumberArrayValue  []float64
	BooleanArrayValue []bool
}

func (c *CreateVectorsUpsertRequestData) SetStringValue(stringValue string) {
	c.StringValue = &stringValue
}

func (c *CreateVectorsUpsertRequestData) GetStringValue() *string {
	if c == nil {
		return nil
	}
	return c.StringValue
}

func (c *CreateVectorsUpsertRequestData) SetIntegerValue(integerValue int64) {
	c.IntegerValue = &integerValue
}

func (c *CreateVectorsUpsertRequestData) GetIntegerValue() *int64 {
	if c == nil {
		return nil
	}
	return c.IntegerValue
}

func (c *CreateVectorsUpsertRequestData) SetNumberValue(numberValue float64) {
	c.NumberValue = &numberValue
}

func (c *CreateVectorsUpsertRequestData) GetNumberValue() *float64 {
	if c == nil {
		return nil
	}
	return c.NumberValue
}

func (c *CreateVectorsUpsertRequestData) SetBooleanValue(booleanValue bool) {
	c.BooleanValue = &booleanValue
}

func (c *CreateVectorsUpsertRequestData) GetBooleanValue() *bool {
	if c == nil {
		return nil
	}
	return c.BooleanValue
}

func (c *CreateVectorsUpsertRequestData) SetStringArrayValue(stringArrayValue []string) {
	c.StringArrayValue = stringArrayValue
}

func (c *CreateVectorsUpsertRequestData) GetStringArrayValue() []string {
	if c == nil {
		return nil
	}
	return c.StringArrayValue
}

func (c *CreateVectorsUpsertRequestData) SetIntegerArrayValue(integerArrayValue []int64) {
	c.IntegerArrayValue = integerArrayValue
}

func (c *CreateVectorsUpsertRequestData) GetIntegerArrayValue() []int64 {
	if c == nil {
		return nil
	}
	return c.IntegerArrayValue
}

func (c *CreateVectorsUpsertRequestData) SetNumberArrayValue(numberArrayValue []float64) {
	c.NumberArrayValue = numberArrayValue
}

func (c *CreateVectorsUpsertRequestData) GetNumberArrayValue() []float64 {
	if c == nil {
		return nil
	}
	return c.NumberArrayValue
}

func (c *CreateVectorsUpsertRequestData) SetBooleanArrayValue(booleanArrayValue []bool) {
	c.BooleanArrayValue = booleanArrayValue
}

func (c *CreateVectorsUpsertRequestData) GetBooleanArrayValue() []bool {
	if c == nil {
		return nil
	}
	return c.BooleanArrayValue
}

func (c CreateVectorsUpsertRequestData) MarshalJSON() ([]byte, error) {
	return marshal.FromComplexObject(c)
}

func (c *CreateVectorsUpsertRequestData) UnmarshalJSON(data []byte) error {
	return unmarshal.ToComplexObject[CreateVectorsUpsertRequestData](data, c)
}
