// This file was generated by liblab | https://liblab.com/

package vectors

type VectorsQueryRequest struct {
	DbName         *string  `json:"dbName,omitempty"`
	CollectionName *string  `json:"collectionName,omitempty" required:"true"`
	PartitionNames []string `json:"partitionNames,omitempty"`
	Filter         *string  `json:"filter,omitempty" required:"true"`
	OutputFields   []string `json:"outputFields,omitempty"`
}

func (c *VectorsQueryRequest) SetDbName(dbName string) {
	c.DbName = &dbName
}

func (c *VectorsQueryRequest) GetDbName() *string {
	if c == nil {
		return nil
	}
	return c.DbName
}

func (c *VectorsQueryRequest) SetCollectionName(collectionName string) {
	c.CollectionName = &collectionName
}

func (c *VectorsQueryRequest) GetCollectionName() *string {
	if c == nil {
		return nil
	}
	return c.CollectionName
}

func (c *VectorsQueryRequest) SetPartitionNames(partitionNames []string) {
	c.PartitionNames = partitionNames
}

func (c *VectorsQueryRequest) GetPartitionNames() []string {
	if c == nil {
		return nil
	}
	return c.PartitionNames
}

func (c *VectorsQueryRequest) SetFilter(filter string) {
	c.Filter = &filter
}

func (c *VectorsQueryRequest) GetFilter() *string {
	if c == nil {
		return nil
	}
	return c.Filter
}

func (c *VectorsQueryRequest) SetOutputFields(outputFields []string) {
	c.OutputFields = outputFields
}

func (c *VectorsQueryRequest) GetOutputFields() []string {
	if c == nil {
		return nil
	}
	return c.OutputFields
}
