// This file was generated by liblab | https://liblab.com/

package vectors

type CreateVectorsDeleteRequest struct {
	DbName         *string `json:"dbName,omitempty"`
	CollectionName *string `json:"collectionName,omitempty" required:"true"`
	Filter         *string `json:"filter,omitempty" required:"true"`
	PartitionName  *string `json:"partitionName,omitempty"`
}

func (c *CreateVectorsDeleteRequest) SetDbName(dbName string) {
	c.DbName = &dbName
}

func (c *CreateVectorsDeleteRequest) GetDbName() *string {
	if c == nil {
		return nil
	}
	return c.DbName
}

func (c *CreateVectorsDeleteRequest) SetCollectionName(collectionName string) {
	c.CollectionName = &collectionName
}

func (c *CreateVectorsDeleteRequest) GetCollectionName() *string {
	if c == nil {
		return nil
	}
	return c.CollectionName
}

func (c *CreateVectorsDeleteRequest) SetFilter(filter string) {
	c.Filter = &filter
}

func (c *CreateVectorsDeleteRequest) GetFilter() *string {
	if c == nil {
		return nil
	}
	return c.Filter
}

func (c *CreateVectorsDeleteRequest) SetPartitionName(partitionName string) {
	c.PartitionName = &partitionName
}

func (c *CreateVectorsDeleteRequest) GetPartitionName() *string {
	if c == nil {
		return nil
	}
	return c.PartitionName
}
