// This file was generated by liblab | https://liblab.com/

package vectors

type CreateVectorsQueryRequest struct {
	DbName         *string  `json:"dbName,omitempty"`
	CollectionName *string  `json:"collectionName,omitempty" required:"true"`
	PartitionNames []string `json:"partitionNames,omitempty"`
	Filter         *string  `json:"filter,omitempty" required:"true"`
	OutputFields   []string `json:"outputFields,omitempty"`
}

func (c *CreateVectorsQueryRequest) SetDbName(dbName string) {
	c.DbName = &dbName
}

func (c *CreateVectorsQueryRequest) GetDbName() *string {
	if c == nil {
		return nil
	}
	return c.DbName
}

func (c *CreateVectorsQueryRequest) SetCollectionName(collectionName string) {
	c.CollectionName = &collectionName
}

func (c *CreateVectorsQueryRequest) GetCollectionName() *string {
	if c == nil {
		return nil
	}
	return c.CollectionName
}

func (c *CreateVectorsQueryRequest) SetPartitionNames(partitionNames []string) {
	c.PartitionNames = partitionNames
}

func (c *CreateVectorsQueryRequest) GetPartitionNames() []string {
	if c == nil {
		return nil
	}
	return c.PartitionNames
}

func (c *CreateVectorsQueryRequest) SetFilter(filter string) {
	c.Filter = &filter
}

func (c *CreateVectorsQueryRequest) GetFilter() *string {
	if c == nil {
		return nil
	}
	return c.Filter
}

func (c *CreateVectorsQueryRequest) SetOutputFields(outputFields []string) {
	c.OutputFields = outputFields
}

func (c *CreateVectorsQueryRequest) GetOutputFields() []string {
	if c == nil {
		return nil
	}
	return c.OutputFields
}
