// This file was generated by liblab | https://liblab.com/

package vectors

import (
	"github.com/swagger-api/swagger-petstore/internal/marshal"
	"github.com/swagger-api/swagger-petstore/internal/unmarshal"
	"github.com/swagger-api/swagger-petstore/internal/utils"
)

type VectorsUpsertRequest struct {
	DbName         *string                              `json:"dbName,omitempty"`
	CollectionName *string                              `json:"collectionName,omitempty" required:"true"`
	PartitionName  *string                              `json:"partitionName,omitempty"`
	Data           map[string]*VectorsUpsertRequestData `json:"data,omitempty"`
}

func (c *VectorsUpsertRequest) SetDbName(dbName string) {
	c.DbName = &dbName
}

func (c *VectorsUpsertRequest) GetDbName() *string {
	if c == nil {
		return nil
	}
	return c.DbName
}

func (c *VectorsUpsertRequest) SetCollectionName(collectionName string) {
	c.CollectionName = &collectionName
}

func (c *VectorsUpsertRequest) GetCollectionName() *string {
	if c == nil {
		return nil
	}
	return c.CollectionName
}

func (c *VectorsUpsertRequest) SetPartitionName(partitionName string) {
	c.PartitionName = &partitionName
}

func (c *VectorsUpsertRequest) GetPartitionName() *string {
	if c == nil {
		return nil
	}
	return c.PartitionName
}

func (c *VectorsUpsertRequest) SetData(data map[string]*VectorsUpsertRequestData) {
	c.Data = utils.CloneMap(data)
}

func (c *VectorsUpsertRequest) GetData() map[string]*VectorsUpsertRequestData {
	if c == nil {
		return nil
	}
	return c.Data
}

type VectorsUpsertRequestData struct {
	StringValue       *string
	IntegerValue      *int64
	NumberValue       *float64
	BooleanValue      *bool
	StringArrayValue  []string
	IntegerArrayValue []int64
	NumberArrayValue  []float64
	BooleanArrayValue []bool
}

func (c *VectorsUpsertRequestData) SetStringValue(stringValue string) {
	c.StringValue = &stringValue
}

func (c *VectorsUpsertRequestData) GetStringValue() *string {
	if c == nil {
		return nil
	}
	return c.StringValue
}

func (c *VectorsUpsertRequestData) SetIntegerValue(integerValue int64) {
	c.IntegerValue = &integerValue
}

func (c *VectorsUpsertRequestData) GetIntegerValue() *int64 {
	if c == nil {
		return nil
	}
	return c.IntegerValue
}

func (c *VectorsUpsertRequestData) SetNumberValue(numberValue float64) {
	c.NumberValue = &numberValue
}

func (c *VectorsUpsertRequestData) GetNumberValue() *float64 {
	if c == nil {
		return nil
	}
	return c.NumberValue
}

func (c *VectorsUpsertRequestData) SetBooleanValue(booleanValue bool) {
	c.BooleanValue = &booleanValue
}

func (c *VectorsUpsertRequestData) GetBooleanValue() *bool {
	if c == nil {
		return nil
	}
	return c.BooleanValue
}

func (c *VectorsUpsertRequestData) SetStringArrayValue(stringArrayValue []string) {
	c.StringArrayValue = stringArrayValue
}

func (c *VectorsUpsertRequestData) GetStringArrayValue() []string {
	if c == nil {
		return nil
	}
	return c.StringArrayValue
}

func (c *VectorsUpsertRequestData) SetIntegerArrayValue(integerArrayValue []int64) {
	c.IntegerArrayValue = integerArrayValue
}

func (c *VectorsUpsertRequestData) GetIntegerArrayValue() []int64 {
	if c == nil {
		return nil
	}
	return c.IntegerArrayValue
}

func (c *VectorsUpsertRequestData) SetNumberArrayValue(numberArrayValue []float64) {
	c.NumberArrayValue = numberArrayValue
}

func (c *VectorsUpsertRequestData) GetNumberArrayValue() []float64 {
	if c == nil {
		return nil
	}
	return c.NumberArrayValue
}

func (c *VectorsUpsertRequestData) SetBooleanArrayValue(booleanArrayValue []bool) {
	c.BooleanArrayValue = booleanArrayValue
}

func (c *VectorsUpsertRequestData) GetBooleanArrayValue() []bool {
	if c == nil {
		return nil
	}
	return c.BooleanArrayValue
}

func (c VectorsUpsertRequestData) MarshalJSON() ([]byte, error) {
	return marshal.FromComplexObject(c)
}

func (c *VectorsUpsertRequestData) UnmarshalJSON(data []byte) error {
	return unmarshal.ToComplexObject[VectorsUpsertRequestData](data, c)
}
