// This file was generated by liblab | https://liblab.com/

package vectors

type VectorsDeleteRequest struct {
	DbName         *string `json:"dbName,omitempty"`
	CollectionName *string `json:"collectionName,omitempty" required:"true"`
	Filter         *string `json:"filter,omitempty" required:"true"`
	PartitionName  *string `json:"partitionName,omitempty"`
}

func (c *VectorsDeleteRequest) SetDbName(dbName string) {
	c.DbName = &dbName
}

func (c *VectorsDeleteRequest) GetDbName() *string {
	if c == nil {
		return nil
	}
	return c.DbName
}

func (c *VectorsDeleteRequest) SetCollectionName(collectionName string) {
	c.CollectionName = &collectionName
}

func (c *VectorsDeleteRequest) GetCollectionName() *string {
	if c == nil {
		return nil
	}
	return c.CollectionName
}

func (c *VectorsDeleteRequest) SetFilter(filter string) {
	c.Filter = &filter
}

func (c *VectorsDeleteRequest) GetFilter() *string {
	if c == nil {
		return nil
	}
	return c.Filter
}

func (c *VectorsDeleteRequest) SetPartitionName(partitionName string) {
	c.PartitionName = &partitionName
}

func (c *VectorsDeleteRequest) GetPartitionName() *string {
	if c == nil {
		return nil
	}
	return c.PartitionName
}
