// This file was generated by liblab | https://liblab.com/

package collections

type Collection struct {
	DbName           *string                 `json:"dbName,omitempty"`
	CollectionName   *string                 `json:"collectionName,omitempty" required:"true"`
	Dimension        *int64                  `json:"dimension,omitempty"`
	MetricType       *string                 `json:"metricType,omitempty"`
	IdType           *string                 `json:"idType,omitempty"`
	AutoId           *string                 `json:"autoID,omitempty"`
	PrimaryFieldName *string                 `json:"primaryFieldName,omitempty"`
	VectorFieldName  *string                 `json:"vectorFieldName,omitempty"`
	Schema           *Schema                 `json:"schema,omitempty"`
	IndexConfig      []IndexParams `json:"indexParams,omitempty"`
	Params           *CollectionParams       `json:"params,omitempty"`
}

func (c *Collection) SetDbName(dbName string) {
	c.DbName = &dbName
}

func (c *Collection) GetDbName() *string {
	if c == nil {
		return nil
	}
	return c.DbName
}

func (c *Collection) SetCollectionName(collectionName string) {
	c.CollectionName = &collectionName
}

func (c *Collection) GetCollectionName() *string {
	if c == nil {
		return nil
	}
	return c.CollectionName
}

func (c *Collection) SetDimension(dimension int64) {
	c.Dimension = &dimension
}

func (c *Collection) GetDimension() *int64 {
	if c == nil {
		return nil
	}
	return c.Dimension
}

func (c *Collection) SetMetricType(metricType string) {
	c.MetricType = &metricType
}

func (c *Collection) GetMetricType() *string {
	if c == nil {
		return nil
	}
	return c.MetricType
}

func (c *Collection) SetIdType(idType string) {
	c.IdType = &idType
}

func (c *Collection) GetIdType() *string {
	if c == nil {
		return nil
	}
	return c.IdType
}

func (c *Collection) SetAutoId(autoId string) {
	c.AutoId = &autoId
}

func (c *Collection) GetAutoId() *string {
	if c == nil {
		return nil
	}
	return c.AutoId
}

func (c *Collection) SetPrimaryFieldName(primaryFieldName string) {
	c.PrimaryFieldName = &primaryFieldName
}

func (c *Collection) GetPrimaryFieldName() *string {
	if c == nil {
		return nil
	}
	return c.PrimaryFieldName
}

func (c *Collection) SetVectorFieldName(vectorFieldName string) {
	c.VectorFieldName = &vectorFieldName
}

func (c *Collection) GetVectorFieldName() *string {
	if c == nil {
		return nil
	}
	return c.VectorFieldName
}

func (c *Collection) SetSchema(schema Schema) {
	c.Schema = &schema
}

func (c *Collection) GetSchema() *Schema {
	if c == nil {
		return nil
	}
	return c.Schema
}

func (c *Collection) SetIndexParams(indexParams []IndexParams) {
	c.IndexConfig = indexParams
}

func (c *Collection) GetIndexParams() []IndexParams {
	if c == nil {
		return nil
	}
	return c.IndexConfig
}

func (c *Collection) SetParams(params CollectionParams) {
	c.Params = &params
}

func (c *Collection) GetParams() *CollectionParams {
	if c == nil {
		return nil
	}
	return c.Params
}

type Schema struct {
	AutoId             *string  `json:"autoID,omitempty"`
	EnableDynamicField *string  `json:"enableDynamicField,omitempty"`
	Field             []Field `json:"fields,omitempty"`
}

func (s *Schema) SetAutoId(autoId string) {
	s.AutoId = &autoId
}

func (s *Schema) GetAutoId() *string {
	if s == nil {
		return nil
	}
	return s.AutoId
}

func (s *Schema) SetEnableDynamicField(enableDynamicField string) {
	s.EnableDynamicField = &enableDynamicField
}

func (s *Schema) GetEnableDynamicField() *string {
	if s == nil {
		return nil
	}
	return s.EnableDynamicField
}

func (s *Schema) SetFields(fields []Field) {
	s.Field = fields
}

func (s *Schema) GetFields() []Field {
	if s == nil {
		return nil
	}
	return s.Field
}

type Field struct {
	FieldName         *string            `json:"fieldName,omitempty"`
	DataType          *string            `json:"dataType,omitempty"`
	ElementDataType   *string            `json:"elementDataType,omitempty"`
	IsPrimary         *bool              `json:"isPrimary,omitempty"`
	IsPartitionKey    *bool              `json:"isPartitionKey,omitempty"`
	ElementTypeParams *ElementTypeParams `json:"elementTypeParams,omitempty"`
}

func (f *Field) SetFieldName(fieldName string) {
	f.FieldName = &fieldName
}

func (f *Field) GetFieldName() *string {
	if f == nil {
		return nil
	}
	return f.FieldName
}

func (f *Field) SetDataType(dataType string) {
	f.DataType = &dataType
}

func (f *Field) GetDataType() *string {
	if f == nil {
		return nil
	}
	return f.DataType
}

func (f *Field) SetElementDataType(elementDataType string) {
	f.ElementDataType = &elementDataType
}

func (f *Field) GetElementDataType() *string {
	if f == nil {
		return nil
	}
	return f.ElementDataType
}

func (f *Field) SetIsPrimary(isPrimary bool) {
	f.IsPrimary = &isPrimary
}

func (f *Field) GetIsPrimary() *bool {
	if f == nil {
		return nil
	}
	return f.IsPrimary
}

func (f *Field) SetIsPartitionKey(isPartitionKey bool) {
	f.IsPartitionKey = &isPartitionKey
}

func (f *Field) GetIsPartitionKey() *bool {
	if f == nil {
		return nil
	}
	return f.IsPartitionKey
}

func (f *Field) SetElementTypeParams(elementTypeParams ElementTypeParams) {
	f.ElementTypeParams = &elementTypeParams
}

func (f *Field) GetElementTypeParams() *ElementTypeParams {
	if f == nil {
		return nil
	}
	return f.ElementTypeParams
}

type ElementTypeParams struct {
	MaxLength   *int64 `json:"max_length,omitempty"`
	Dim         *int64 `json:"dim,omitempty"`
	MaxCapacity *int64 `json:"max_capacity,omitempty"`
}

func (e *ElementTypeParams) SetMaxLength(maxLength int64) {
	e.MaxLength = &maxLength
}

func (e *ElementTypeParams) GetMaxLength() *int64 {
	if e == nil {
		return nil
	}
	return e.MaxLength
}

func (e *ElementTypeParams) SetDim(dim int64) {
	e.Dim = &dim
}

func (e *ElementTypeParams) GetDim() *int64 {
	if e == nil {
		return nil
	}
	return e.Dim
}

func (e *ElementTypeParams) SetMaxCapacity(maxCapacity int64) {
	e.MaxCapacity = &maxCapacity
}

func (e *ElementTypeParams) GetMaxCapacity() *int64 {
	if e == nil {
		return nil
	}
	return e.MaxCapacity
}

type IndexParams struct {
	MetricType *string      `json:"metricType,omitempty"`
	FieldName  *string      `json:"fieldName,omitempty"`
	IndexName  *string      `json:"indexName,omitempty"`
	Params     *IndexConfig `json:"params,omitempty"`
}

func (c *IndexParams) SetMetricType(metricType string) {
	c.MetricType = &metricType
}

func (c *IndexParams) GetMetricType() *string {
	if c == nil {
		return nil
	}
	return c.MetricType
}

func (c *IndexParams) SetFieldName(fieldName string) {
	c.FieldName = &fieldName
}

func (c *IndexParams) GetFieldName() *string {
	if c == nil {
		return nil
	}
	return c.FieldName
}

func (c *IndexParams) SetIndexName(indexName string) {
	c.IndexName = &indexName
}

func (c *IndexParams) GetIndexName() *string {
	if c == nil {
		return nil
	}
	return c.IndexName
}

func (c *IndexParams) SetParams(params IndexConfig) {
	c.Params = &params
}

func (c *IndexParams) GetParams() *IndexConfig {
	if c == nil {
		return nil
	}
	return c.Params
}

type IndexConfig struct {
	IndexType      *string `json:"index_type,omitempty"`
	M              *int64  `json:"M,omitempty"`
	EfConstruction *int64  `json:"efConstruction,omitempty"`
	Nlist          *int64  `json:"nlist,omitempty"`
}

func (i *IndexConfig) SetIndexType(indexType string) {
	i.IndexType = &indexType
}

func (i *IndexConfig) GetIndexType() *string {
	if i == nil {
		return nil
	}
	return i.IndexType
}

func (i *IndexConfig) SetM(m int64) {
	i.M = &m
}

func (i *IndexConfig) GetM() *int64 {
	if i == nil {
		return nil
	}
	return i.M
}

func (i *IndexConfig) SetEfConstruction(efConstruction int64) {
	i.EfConstruction = &efConstruction
}

func (i *IndexConfig) GetEfConstruction() *int64 {
	if i == nil {
		return nil
	}
	return i.EfConstruction
}

func (i *IndexConfig) SetNlist(nlist int64) {
	i.Nlist = &nlist
}

func (i *IndexConfig) GetNlist() *int64 {
	if i == nil {
		return nil
	}
	return i.Nlist
}

type CollectionParams struct {
	MaxLength          *int64 `json:"max_length,omitempty"`
	EnableDynamicField *bool  `json:"enableDynamicField,omitempty"`
	ShardsNum          *int64 `json:"shardsNum,omitempty"`
	ConsistencyLevel   *int64 `json:"consistencyLevel,omitempty"`
	PartitionsNum      *int64 `json:"partitionsNum,omitempty"`
	TtlSeconds         *int64 `json:"ttlSeconds,omitempty"`
}

func (c *CollectionParams) SetMaxLength(maxLength int64) {
	c.MaxLength = &maxLength
}

func (c *CollectionParams) GetMaxLength() *int64 {
	if c == nil {
		return nil
	}
	return c.MaxLength
}

func (c *CollectionParams) SetEnableDynamicField(enableDynamicField bool) {
	c.EnableDynamicField = &enableDynamicField
}

func (c *CollectionParams) GetEnableDynamicField() *bool {
	if c == nil {
		return nil
	}
	return c.EnableDynamicField
}

func (c *CollectionParams) SetShardsNum(shardsNum int64) {
	c.ShardsNum = &shardsNum
}

func (c *CollectionParams) GetShardsNum() *int64 {
	if c == nil {
		return nil
	}
	return c.ShardsNum
}

func (c *CollectionParams) SetConsistencyLevel(consistencyLevel int64) {
	c.ConsistencyLevel = &consistencyLevel
}

func (c *CollectionParams) GetConsistencyLevel() *int64 {
	if c == nil {
		return nil
	}
	return c.ConsistencyLevel
}

func (c *CollectionParams) SetPartitionsNum(partitionsNum int64) {
	c.PartitionsNum = &partitionsNum
}

func (c *CollectionParams) GetPartitionsNum() *int64 {
	if c == nil {
		return nil
	}
	return c.PartitionsNum
}

func (c *CollectionParams) SetTtlSeconds(ttlSeconds int64) {
	c.TtlSeconds = &ttlSeconds
}

func (c *CollectionParams) GetTtlSeconds() *int64 {
	if c == nil {
		return nil
	}
	return c.TtlSeconds
}
