// This file was generated by liblab | https://liblab.com/

package collections

type CreateCollectionsRenameRequest struct {
	DbName            *string `json:"dbName,omitempty"`
	CollectionName    *string `json:"collectionName,omitempty" required:"true"`
	NewCollectionName *string `json:"newCollectionName,omitempty" required:"true"`
}

func (c *CreateCollectionsRenameRequest) SetDbName(dbName string) {
	c.DbName = &dbName
}

func (c *CreateCollectionsRenameRequest) GetDbName() *string {
	if c == nil {
		return nil
	}
	return c.DbName
}

func (c *CreateCollectionsRenameRequest) SetCollectionName(collectionName string) {
	c.CollectionName = &collectionName
}

func (c *CreateCollectionsRenameRequest) GetCollectionName() *string {
	if c == nil {
		return nil
	}
	return c.CollectionName
}

func (c *CreateCollectionsRenameRequest) SetNewCollectionName(newCollectionName string) {
	c.NewCollectionName = &newCollectionName
}

func (c *CreateCollectionsRenameRequest) GetNewCollectionName() *string {
	if c == nil {
		return nil
	}
	return c.NewCollectionName
}
