// This file was generated by liblab | https://liblab.com/

package collections

type CollectionDescribeRequest struct {
	DbName         *string `json:"dbName,omitempty"`
	CollectionName *string `json:"collectionName,omitempty" required:"true"`
}

func (c *CollectionDescribeRequest) SetDbName(dbName string) {
	c.DbName = &dbName
}

func (c *CollectionDescribeRequest) GetDbName() *string {
	if c == nil {
		return nil
	}
	return c.DbName
}

func (c *CollectionDescribeRequest) SetCollectionName(collectionName string) {
	c.CollectionName = &collectionName
}

func (c *CollectionDescribeRequest) GetCollectionName() *string {
	if c == nil {
		return nil
	}
	return c.CollectionName
}
