// This file was generated by liblab | https://liblab.com/

package collections

type CollectionListRequest struct {
	DbName *string `json:"dbName,omitempty" required:"true"`
}

func (c *CollectionListRequest) SetDbName(dbName string) {
	c.DbName = &dbName
}

func (c *CollectionListRequest) GetDbName() *string {
	if c == nil {
		return nil
	}
	return c.DbName
}
