// This file was generated by liblab | https://liblab.com/

package collections

type CreateCollectionsListRequest struct {
	DbName *string `json:"dbName,omitempty" required:"true"`
}

func (c *CreateCollectionsListRequest) SetDbName(dbName string) {
	c.DbName = &dbName
}

func (c *CreateCollectionsListRequest) GetDbName() *string {
	if c == nil {
		return nil
	}
	return c.DbName
}
