// This file was generated by liblab | https://liblab.com/

package collections

type CreateCollectionsGetLoadStateRequest struct {
	DbName         *string `json:"dbName,omitempty"`
	CollectionName *string `json:"collectionName,omitempty" required:"true"`
	PartitionNames *string `json:"partitionNames,omitempty"`
}

func (c *CreateCollectionsGetLoadStateRequest) SetDbName(dbName string) {
	c.DbName = &dbName
}

func (c *CreateCollectionsGetLoadStateRequest) GetDbName() *string {
	if c == nil {
		return nil
	}
	return c.DbName
}

func (c *CreateCollectionsGetLoadStateRequest) SetCollectionName(collectionName string) {
	c.CollectionName = &collectionName
}

func (c *CreateCollectionsGetLoadStateRequest) GetCollectionName() *string {
	if c == nil {
		return nil
	}
	return c.CollectionName
}

func (c *CreateCollectionsGetLoadStateRequest) SetPartitionNames(partitionNames string) {
	c.PartitionNames = &partitionNames
}

func (c *CreateCollectionsGetLoadStateRequest) GetPartitionNames() *string {
	if c == nil {
		return nil
	}
	return c.PartitionNames
}
