// This file was generated by liblab | https://liblab.com/

package io.gandi.models;

@lombok.Getter
@lombok.EqualsAndHashCode(callSuper = false)
@lombok.ToString
@com.fasterxml.jackson.annotation.JsonInclude(com.fasterxml.jackson.annotation.JsonInclude.Include.NON_NULL)
@com.fasterxml.jackson.databind.annotation.JsonDeserialize(builder = Create2Request.Builder.class)
public class Create2Request extends io.gandi.models.BaseModel {

  @lombok.Getter
  @lombok.Setter
  @lombok.experimental.Accessors(chain = true)
  @com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder(
    buildMethodName = "buildWithoutValidation",
    withPrefix = "set"
  )
  public static class Builder extends io.gandi.models.BaseModel.Builder {

    static final java.util.Set<java.util.Set<String>> REQUIRED_FIELDS_GROUPS;

    static {
      java.lang.String[][] requiredFieldsGroups = new java.lang.String[][] {
        new java.lang.String[] { "collectionName" },
      };

      REQUIRED_FIELDS_GROUPS =
        java.util.Arrays
          .stream(requiredFieldsGroups)
          .map(group -> java.util.Arrays.stream(group).collect(java.util.stream.Collectors.toSet()))
          .collect(java.util.stream.Collectors.toSet());
    }

    @com.fasterxml.jackson.annotation.JsonProperty("collectionName")
    private java.lang.String collectionName;

    @com.fasterxml.jackson.annotation.JsonProperty("dbName")
    private java.lang.String dbName;

    public Builder() {
      super(ValidationType.ALL_OF);
    }

    protected Builder(BaseModel.Builder.ValidationType validationType) {
      super(validationType);
    }

    public Create2Request build() {
      String validateMsg = validate();

      if (validateMsg != null) {
        throw new io.gandi.exceptions.ApiException(validateMsg);
      }

      return buildWithoutValidation();
    }

    public Create2Request buildWithoutValidation() {
      return new Create2Request(this);
    }

    @Override
    protected java.util.Set<String> getNonNullInstanceFieldNames() {
      // Introspect the class to get a list of all declared fields.
      return java.util.Arrays
        .stream(this.getClass().getDeclaredFields())
        .filter(field -> {
          try {
            // Filter fields that are non-static and have values that are not null.
            return (!java.lang.reflect.Modifier.isStatic(field.getModifiers()) && field.get(this) != null);
          } catch (IllegalArgumentException | IllegalAccessException e) {
            // This should never happen...

            throw new io.gandi.exceptions.ApiException(
              "Unexpected exception thrown while accessing instance fields.",
              e
            );
          }
        })
        .map(java.lang.reflect.Field::getName)
        .collect(java.util.stream.Collectors.toSet());
    }

    @Override
    protected java.util.Set<java.util.Set<String>> getRequiredFieldsGroups() {
      return REQUIRED_FIELDS_GROUPS;
    }
  }

  @com.fasterxml.jackson.annotation.JsonProperty("collectionName")
  private final java.lang.String collectionName;

  @com.fasterxml.jackson.annotation.JsonProperty("dbName")
  private final java.lang.String dbName;

  Create2Request(Builder builder) {
    super(builder);
    this.collectionName = builder.getCollectionName();
    this.dbName = builder.getDbName();
  }
}
