// This file was generated by liblab | https://liblab.com/

package io.gandi.models;

@lombok.Getter
@lombok.EqualsAndHashCode(callSuper = false)
@lombok.ToString
@com.fasterxml.jackson.annotation.JsonInclude(com.fasterxml.jackson.annotation.JsonInclude.Include.NON_NULL)
@com.fasterxml.jackson.databind.annotation.JsonDeserialize(builder = Create19Request.Builder.class)
public class Create19Request extends io.gandi.models.BaseModel {

  @lombok.Getter
  @lombok.EqualsAndHashCode(callSuper = false)
  @lombok.ToString
  @com.fasterxml.jackson.annotation.JsonInclude(com.fasterxml.jackson.annotation.JsonInclude.Include.NON_NULL)
  @com.fasterxml.jackson.databind.annotation.JsonDeserialize(builder = Create19Request.SearchParams.Builder.class)
  public static class SearchParams extends io.gandi.models.BaseModel {

    @lombok.Getter
    @lombok.EqualsAndHashCode(callSuper = false)
    @lombok.ToString
    @com.fasterxml.jackson.annotation.JsonInclude(com.fasterxml.jackson.annotation.JsonInclude.Include.NON_NULL)
    @com.fasterxml.jackson.databind.annotation.JsonDeserialize(
      builder = Create19Request.SearchParams.Params.Builder.class
    )
    public static class Params extends io.gandi.models.BaseModel {

      @lombok.Getter
      @lombok.Setter
      @lombok.experimental.Accessors(chain = true)
      @com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder(
        buildMethodName = "buildWithoutValidation",
        withPrefix = "set"
      )
      public static class Builder extends io.gandi.models.BaseModel.Builder {

        static final java.util.Set<java.util.Set<String>> REQUIRED_FIELDS_GROUPS;

        static {
          java.lang.String[][] requiredFieldsGroups = new java.lang.String[][] {};

          REQUIRED_FIELDS_GROUPS =
            java.util.Arrays
              .stream(requiredFieldsGroups)
              .map(group -> java.util.Arrays.stream(group).collect(java.util.stream.Collectors.toSet()))
              .collect(java.util.stream.Collectors.toSet());
        }

        @com.fasterxml.jackson.annotation.JsonProperty("radius")
        private java.lang.Long radius;

        @com.fasterxml.jackson.annotation.JsonProperty("range_filter")
        private java.lang.Long rangeFilter;

        public Builder() {
          super(ValidationType.ALL_OF);
        }

        protected Builder(BaseModel.Builder.ValidationType validationType) {
          super(validationType);
        }

        public Create19Request.SearchParams.Params build() {
          String validateMsg = validate();

          if (validateMsg != null) {
            throw new io.gandi.exceptions.ApiException(validateMsg);
          }

          return buildWithoutValidation();
        }

        public Create19Request.SearchParams.Params buildWithoutValidation() {
          return new Create19Request.SearchParams.Params(this);
        }

        @Override
        protected java.util.Set<String> getNonNullInstanceFieldNames() {
          // Introspect the class to get a list of all declared fields.
          return java.util.Arrays
            .asList(this.getClass().getDeclaredFields())
            .stream()
            .filter(field -> {
              try {
                // Filter fields that are non-static and have values that are not null.
                return (!java.lang.reflect.Modifier.isStatic(field.getModifiers()) && field.get(this) != null);
              } catch (IllegalArgumentException | IllegalAccessException e) {
                // This should never happen...

                throw new io.gandi.exceptions.ApiException(
                  "Unexpected exception thrown while accessing instance fields.",
                  e
                );
              }
            })
            .map(java.lang.reflect.Field::getName)
            .collect(java.util.stream.Collectors.toSet());
        }

        @Override
        protected java.util.Set<java.util.Set<String>> getRequiredFieldsGroups() {
          return REQUIRED_FIELDS_GROUPS;
        }
      }

      @com.fasterxml.jackson.annotation.JsonProperty("radius")
      private final java.lang.Long radius;

      @com.fasterxml.jackson.annotation.JsonProperty("range_filter")
      private final java.lang.Long rangeFilter;

      Params(Builder builder) {
        super(builder);
        this.radius = builder.getRadius();
        this.rangeFilter = builder.getRangeFilter();
      }
    }

    @lombok.Getter
    @lombok.Setter
    @lombok.experimental.Accessors(chain = true)
    @com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder(
      buildMethodName = "buildWithoutValidation",
      withPrefix = "set"
    )
    public static class Builder extends io.gandi.models.BaseModel.Builder {

      static final java.util.Set<java.util.Set<String>> REQUIRED_FIELDS_GROUPS;

      static {
        java.lang.String[][] requiredFieldsGroups = new java.lang.String[][] {};

        REQUIRED_FIELDS_GROUPS =
          java.util.Arrays
            .stream(requiredFieldsGroups)
            .map(group -> java.util.Arrays.stream(group).collect(java.util.stream.Collectors.toSet()))
            .collect(java.util.stream.Collectors.toSet());
      }

      @com.fasterxml.jackson.annotation.JsonProperty("metricType")
      private java.lang.String metricType;

      @com.fasterxml.jackson.annotation.JsonProperty("params")
      private Create19Request.SearchParams.Params params;

      public Builder() {
        super(ValidationType.ALL_OF);
      }

      protected Builder(BaseModel.Builder.ValidationType validationType) {
        super(validationType);
      }

      public Create19Request.SearchParams build() {
        String validateMsg = validate();

        if (validateMsg != null) {
          throw new io.gandi.exceptions.ApiException(validateMsg);
        }

        return buildWithoutValidation();
      }

      public Create19Request.SearchParams buildWithoutValidation() {
        return new Create19Request.SearchParams(this);
      }

      @Override
      protected java.util.Set<String> getNonNullInstanceFieldNames() {
        // Introspect the class to get a list of all declared fields.
        return java.util.Arrays
          .asList(this.getClass().getDeclaredFields())
          .stream()
          .filter(field -> {
            try {
              // Filter fields that are non-static and have values that are not null.
              return (!java.lang.reflect.Modifier.isStatic(field.getModifiers()) && field.get(this) != null);
            } catch (IllegalArgumentException | IllegalAccessException e) {
              // This should never happen...

              throw new io.gandi.exceptions.ApiException(
                "Unexpected exception thrown while accessing instance fields.",
                e
              );
            }
          })
          .map(java.lang.reflect.Field::getName)
          .collect(java.util.stream.Collectors.toSet());
      }

      @Override
      protected java.util.Set<java.util.Set<String>> getRequiredFieldsGroups() {
        return REQUIRED_FIELDS_GROUPS;
      }
    }

    @com.fasterxml.jackson.annotation.JsonProperty("metricType")
    private final java.lang.String metricType;

    @com.fasterxml.jackson.annotation.JsonProperty("params")
    private final Create19Request.SearchParams.Params params;

    SearchParams(Builder builder) {
      super(builder);
      this.metricType = builder.getMetricType();
      this.params = builder.getParams();
    }
  }

  @lombok.Getter
  @lombok.Setter
  @lombok.experimental.Accessors(chain = true)
  @com.fasterxml.jackson.databind.annotation.JsonPOJOBuilder(
    buildMethodName = "buildWithoutValidation",
    withPrefix = "set"
  )
  public static class Builder extends io.gandi.models.BaseModel.Builder {

    static final java.util.Set<java.util.Set<String>> REQUIRED_FIELDS_GROUPS;

    static {
      java.lang.String[][] requiredFieldsGroups = new java.lang.String[][] {
        new java.lang.String[] { "collectionName" },
      };

      REQUIRED_FIELDS_GROUPS =
        java.util.Arrays
          .stream(requiredFieldsGroups)
          .map(group -> java.util.Arrays.stream(group).collect(java.util.stream.Collectors.toSet()))
          .collect(java.util.stream.Collectors.toSet());
    }

    @com.fasterxml.jackson.annotation.JsonProperty("anssField")
    private java.lang.String anssField;

    @com.fasterxml.jackson.annotation.JsonProperty("collectionName")
    private java.lang.String collectionName;

    @com.fasterxml.jackson.annotation.JsonProperty("dbName")
    private java.lang.String dbName;

    @com.fasterxml.jackson.annotation.JsonProperty("filter")
    private java.lang.String filter;

    @com.fasterxml.jackson.annotation.JsonProperty("groupingField")
    private java.lang.String groupingField;

    @com.fasterxml.jackson.annotation.JsonProperty("limit")
    private java.lang.Long limit;

    @com.fasterxml.jackson.annotation.JsonProperty("offset")
    private java.lang.Long offset;

    @com.fasterxml.jackson.annotation.JsonProperty("outputFields")
    private java.util.List<java.lang.String> outputFields;

    @com.fasterxml.jackson.annotation.JsonProperty("partitionNames")
    private java.util.List<java.lang.String> partitionNames;

    @com.fasterxml.jackson.annotation.JsonProperty("searchParams")
    private Create19Request.SearchParams searchParams;

    public Builder() {
      super(ValidationType.ALL_OF);
    }

    protected Builder(BaseModel.Builder.ValidationType validationType) {
      super(validationType);
    }

    public Create19Request build() {
      String validateMsg = validate();

      if (validateMsg != null) {
        throw new io.gandi.exceptions.ApiException(validateMsg);
      }

      return buildWithoutValidation();
    }

    public Create19Request buildWithoutValidation() {
      return new Create19Request(this);
    }

    @Override
    protected java.util.Set<String> getNonNullInstanceFieldNames() {
      // Introspect the class to get a list of all declared fields.
      return java.util.Arrays
        .stream(this.getClass().getDeclaredFields())
        .filter(field -> {
          try {
            // Filter fields that are non-static and have values that are not null.
            return (!java.lang.reflect.Modifier.isStatic(field.getModifiers()) && field.get(this) != null);
          } catch (IllegalArgumentException | IllegalAccessException e) {
            // This should never happen...

            throw new io.gandi.exceptions.ApiException(
              "Unexpected exception thrown while accessing instance fields.",
              e
            );
          }
        })
        .map(java.lang.reflect.Field::getName)
        .collect(java.util.stream.Collectors.toSet());
    }

    @Override
    protected java.util.Set<java.util.Set<String>> getRequiredFieldsGroups() {
      return REQUIRED_FIELDS_GROUPS;
    }
  }

  @com.fasterxml.jackson.annotation.JsonProperty("anssField")
  private final java.lang.String anssField;

  @com.fasterxml.jackson.annotation.JsonProperty("collectionName")
  private final java.lang.String collectionName;

  @com.fasterxml.jackson.annotation.JsonProperty("dbName")
  private final java.lang.String dbName;

  @com.fasterxml.jackson.annotation.JsonProperty("filter")
  private final java.lang.String filter;

  @com.fasterxml.jackson.annotation.JsonProperty("groupingField")
  private final java.lang.String groupingField;

  @com.fasterxml.jackson.annotation.JsonProperty("limit")
  private final java.lang.Long limit;

  @com.fasterxml.jackson.annotation.JsonProperty("offset")
  private final java.lang.Long offset;

  @com.fasterxml.jackson.annotation.JsonProperty("outputFields")
  private final java.util.List<java.lang.String> outputFields;

  @com.fasterxml.jackson.annotation.JsonProperty("partitionNames")
  private final java.util.List<java.lang.String> partitionNames;

  @com.fasterxml.jackson.annotation.JsonProperty("searchParams")
  private final Create19Request.SearchParams searchParams;

  Create19Request(Builder builder) {
    super(builder);
    this.anssField = builder.getAnssField();
    this.collectionName = builder.getCollectionName();
    this.dbName = builder.getDbName();
    this.filter = builder.getFilter();
    this.groupingField = builder.getGroupingField();
    this.limit = builder.getLimit();
    this.offset = builder.getOffset();
    this.outputFields = builder.getOutputFields();
    this.partitionNames = builder.getPartitionNames();
    this.searchParams = builder.getSearchParams();
  }
}
