apiVersion: v1
kind: Service
metadata:
  name: milvus-db-service-{{ .Release.Name }}
  namespace: {{ .Values.Namespace}}
  labels:
    app: milvus
spec:
  ports:
    - port: {{ .Values.Port }}
      targetPort: 19530
  selector:
    app: milvus
    tier: db
    release: {{ .Release.Name }}
  type: NodePort
