// This file was generated by liblab | https://liblab.com/

package io.gandi.http;

import io.gandi.exceptions.ApiException;
import java.util.List;

public interface CollectionsClient {
  String create(io.gandi.models.CollectionRequest input) throws ApiException;
  String create2(io.gandi.models.Create2Request input) throws ApiException;
  String create3(io.gandi.models.Create3Request input) throws ApiException;
  String create4(io.gandi.models.Create4Request input) throws ApiException;
  String create5(io.gandi.models.Create5Request input) throws ApiException;
  String create6(io.gandi.models.Create6Request input) throws ApiException;
  String create7(io.gandi.models.Create7Request input) throws ApiException;
  String create8(io.gandi.models.Create8Request input) throws ApiException;
  String create9(io.gandi.models.Create9Request input) throws ApiException;
  String create10(io.gandi.models.Create10Request input) throws ApiException;
}
