// This file was generated by liblab | https://liblab.com/

package io.gandi.http;

import io.gandi.exceptions.ApiException;
import java.util.List;

public interface IndexesClient {
  String create11(io.gandi.models.IndexRequest input) throws ApiException;
  String create12(io.gandi.models.Create12Request input) throws ApiException;
  String create13(io.gandi.models.Create13Request input) throws ApiException;
  String create14(io.gandi.models.Create14Request input) throws ApiException;
}
