// This file was generated by liblab | https://liblab.com/

package io.gandi.http;

import io.gandi.exceptions.ApiException;
import java.util.List;

public interface VectorsClient {
  String create15(io.gandi.models.Create15Request input) throws ApiException;
  String create16(io.gandi.models.Create16Request input) throws ApiException;
  String create17(io.gandi.models.Create17Request input) throws ApiException;
  String create18(io.gandi.models.Create18Request input) throws ApiException;
  String create19(io.gandi.models.Create19Request input) throws ApiException;
  String create20(io.gandi.models.Create20Request input) throws ApiException;
}
