// This file was generated by liblab | https://liblab.com/

package io.gandi.services;

import io.gandi.exceptions.ApiException;
import io.gandi.http.*;
import io.gandi.http.util.HttpHeaders;
import io.gandi.http.util.HttpUrl;
import io.gandi.models.BaseModel;
import java.io.IOException;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import okhttp3.Headers;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.RequestBody;
import okhttp3.Response;

public class IndexesService extends BaseService implements IndexesClient {

  public IndexesService(OkHttpClient httpClient, String serverUrl) {
    super(httpClient, serverUrl);
  }

  /**
   * @summary Create a new index
   */
  public String create11(io.gandi.models.IndexRequest input) throws ApiException {
    String url = HttpUrl.builder(this.serverUrl).addPathParameter("indexes").addPathParameter("create").build();
    RequestBody requestBody = RequestBody.create(
      Objects.requireNonNull(ModelConverter.modelToJson(input)),
      okhttp3.MediaType.parse("application/json; charset=utf-8")
    );
    Request request = new Request.Builder().url(url).post(requestBody).build();
    Response response = this.execute(request);

    try {
      return response.body().string();
    } catch (IOException e) {
      e.printStackTrace();
    }
    return null;
  }

  /**
   * @summary Describe an index
   */
  public String create12(io.gandi.models.Create12Request input) throws ApiException {
    String url = HttpUrl.builder(this.serverUrl).addPathParameter("indexes").addPathParameter("describe").build();
    RequestBody requestBody = RequestBody.create(
      Objects.requireNonNull(ModelConverter.modelToJson(input)),
      okhttp3.MediaType.parse("application/json; charset=utf-8")
    );
    Request request = new Request.Builder().url(url).post(requestBody).build();
    Response response = this.execute(request);

    try {
      return response.body().string();
    } catch (IOException e) {
      e.printStackTrace();
    }
    return null;
  }

  /**
   * @summary Drop an index
   */
  public String create13(io.gandi.models.Create13Request input) throws ApiException {
    String url = HttpUrl.builder(this.serverUrl).addPathParameter("indexes").addPathParameter("drop").build();
    RequestBody requestBody = RequestBody.create(
      Objects.requireNonNull(ModelConverter.modelToJson(input)),
      okhttp3.MediaType.parse("application/json; charset=utf-8")
    );
    Request request = new Request.Builder().url(url).post(requestBody).build();
    Response response = this.execute(request);

    try {
      return response.body().string();
    } catch (IOException e) {
      e.printStackTrace();
    }
    return null;
  }

  /**
   * @summary List all indexes
   */
  public String create14(io.gandi.models.Create14Request input) throws ApiException {
    String url = HttpUrl.builder(this.serverUrl).addPathParameter("indexes").addPathParameter("list").build();
    RequestBody requestBody = RequestBody.create(
      Objects.requireNonNull(ModelConverter.modelToJson(input)),
      okhttp3.MediaType.parse("application/json; charset=utf-8")
    );
    Request request = new Request.Builder().url(url).post(requestBody).build();
    Response response = this.execute(request);

    try {
      return response.body().string();
    } catch (IOException e) {
      e.printStackTrace();
    }
    return null;
  }
}
